### PR TITLE
Fixes potential max value overflow when parsing Clojure data into Java data

### PR DESCRIPTION
**Pull request by jordanrobinson**
Hello, 

Please see attached commit for details. The test will fail against the current code, with the fix being to parse as Long by default. This is because `number?` encompasses both Integer and Long.

Thanks,
Jordan

### CODE REVIEW

**Comment by tobyclemson** [comment]
Hey @jordanrobinson,

I'm confused what happened here. Not only did the PR closed but it's contents disappeared?

Thanks,
Toby

**Comment by tobyclemson** [comment]
Is the PR no longer relevant?

**Comment by jordanrobinson** [comment]
Hey @tobyclemson, it was about a year old and there were conflicts, so I'm fixing the branch up, it looks like when it rebased it auto-closed this as the commit didn't exist any more on that branch. I'll supply a new one shortly.

**Comment by jordanrobinson** [comment]
Reopened as #7 - let me know if any questions.

**Pull request closed without merging**
